export const tempData = [
    {
      id: "123456",
      name: "Server A",
      description: "Production server",
      status: 1,
    },
    { id: "123457", name: "Server B", description: "Backup server", status: 2 },
    { id: "123458", name: "Website", description: "Frontend server", status: 1 },
    { id: "123459", name: "Database", description: "Data storage", status: 2 },
    {
      id: "123460",
      name: "API Gateway",
      description: "Backend API service",
      status: 1,
    },
    {
      id: "123461",
      name: "Load Balancer",
      description: "Traffic distribution",
      status: 1,
    },
    {
      id: "123462",
      name: "Cache Server",
      description: "Caching system",
      status: 1,
    },
    {
      id: "123463",
      name: "Monitoring Service",
      description: "Health check service",
      status: 1,
    },
    {
      id: "123464",
      name: "Notification Service",
      description: "Alerting service",
      status: 2,
    },
    {
      id: "123465",
      name: "Logging Server",
      description: "Log management",
      status: 1,
    },
    {
      id: "123466",
      name: "Email Server",
      description: "Email delivery service",
      status: 1,
    },
    {
      id: "123467",
      name: "Backup Storage",
      description: "Data backup solution",
      status: 2,
    },
    {
      id: "123468",
      name: "Authentication Service",
      description: "User authentication",
      status: 1,
    },
    {
      id: "123469",
      name: "Search Engine",
      description: "Full-text search service",
      status: 2,
    },
    {
      id: "123470",
      name: "Dashboard",
      description: "Monitoring dashboard",
      status: 1,
    },
    {
      id: "123471",
      name: "Billing System",
      description: "Payment processing",
      status: 1,
    },
    {
      id: "123472",
      name: "Analytics Platform",
      description: "Data analysis tool",
      status: 1,
    },
    {
      id: "123473",
      name: "File Storage",
      description: "File hosting service",
      status: 1,
    },
    {
      id: "123474",
      name: "Task Scheduler",
      description: "Job scheduling service",
      status: 2,
    },
    {
      id: "123475",
      name: "Customer Support",
      description: "Helpdesk system",
      status: 1,
    },
    {
      id: "123476",
      name: "Backup Server C",
      description: "Secondary backup server",
      status: 2,
    },
    {
      id: "123477",
      name: "Content Delivery Network",
      description: "CDN service",
      status: 1,
    },
    {
      id: "123478",
      name: "API Service 2",
      description: "Additional API endpoint",
      status: 1,
    },
    {
      id: "123479",
      name: "Payment Gateway",
      description: "Transaction processing",
      status: 2,
    },
    {
      id: "123480",
      name: "Database Cluster",
      description: "Distributed database",
      status: 1,
    },
    {
      id: "123481",
      name: "Load Testing Service",
      description: "Performance testing",
      status: 1,
    },
    {
      id: "123482",
      name: "Backup Generator",
      description: "Power backup system",
      status: 1,
    },
    {
      id: "123483",
      name: "API Gateway 2",
      description: "Secondary API service",
      status: 1,
    },
    {
      id: "123484",
      name: "DNS Server",
      description: "Domain name resolution",
      status: 1,
    },
    {
      id: "123485",
      name: "VoIP Service",
      description: "Voice over IP",
      status: 2,
    },
    {
      id: "123486",
      name: "Data Warehouse",
      description: "Big data storage",
      status: 1,
    },
  ];